---
env_type: open-environment-aap-azure
# This var is used to identify stack (cloudformation, azure resourcegroup, ...)
project_tag: "{{ env_type }}-{{ guid }}"
output_dir: "/tmp/output-dir-{{ guid }}"
az_function_get: "https://{{az_function_hostname}}/api/get/"
az_function_release: "https://{{az_function_hostname}}/api/release/"
az_function_show: "https://{{az_function_hostname}}/api/show/"