---
- name: Cleanup Azure Sandbox
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AZURE_CONFIG_DIR: "{{ output_dir }}/.azure-{{ project_tag }}"
  tasks:
    - name: Run the azure remove user from subscription ROLE
      include_role:
        name: open-env-azure-remove-user-from-subscription
