---
- name: Initialize azureProfile.json
  command: >
    az login --service-principal -u {{ azure_service_principal }}
    -p {{ azure_password }} --tenant {{ azure_tenant }}
- name: Get CICD User Default
  set_fact:
    cicd_user: "{{ open_env_azure_cicd_user | default('jenkins.sfo01@gmail.com') }}"
- name: Check if email is Red Hat associate or CICD User
  fail:
    msg: User is not a Red Hat associate or CICD User
  when:
    - '"@redhat.com" not in email'
    - 'cicd_user not in email'
- name: Set Up UPN for Red Hat Associate
  when:
    - '"@redhat.com" in email'
  set_fact:
    upn: "{{ email }}"

- name: Checking if user is in Active Directory
  azure.azcollection.azure_rm_aduser_info:
    auth_source: cli
    user_principal_name: "{{ email }}"
    tenant: "{{ azure_tenant }}"
  register: azuser

- name: Get facts for subscriptions containing tags AVAILABLE.
  azure.azcollection.azure_rm_subscription_info:
    auth_source: cli
    all: True
  register: available_subs

- name: print out subscriptions 
  debug:
    msg: "{{ available_subs}}"

- name: Get the first subscriptions AVAILABLE.
  set_fact:
    first_available_sub: "{{ available_subs['subscriptions']|selectattr('tags.AVAILABLE', 'defined')|selectattr('tags.AVAILABLE', 'eq', 'TRUE') | first }}"

- name: write out the first Subscription
  debug:
    msg: "{{ first_available_sub }}"

- name: Tag the Azure subscription to not available, and with the users email and guid
  command: >
    az tag create --resource-id {{ first_available_sub.fqid }} --tags AVAILABLE=FALSE GUID={{ guid }} EMAIL={{ email }}

- name: Get CONTRIBUTOR Role Definition
  azure.azcollection.azure_rm_roledefinition_info:
    auth_source: cli
    scope: "{{ first_available_sub.fqid }}"
    role_name: Contributor
  register: contributor_role_definition

- name: Make user CONTRIBUTOR on the subscription
  azure.azcollection.azure_rm_roleassignment:
    auth_source: cli
    scope: "{{ first_available_sub.fqid }}"
    assignee_object_id: "{{ azuser['ad_users'][0].object_id }}"
    role_definition_id:
      "{{ contributor_role_definition['roledefinitions'][0].id }}"
    state: present
